# Análise Exploratória de Dados (AED)

## 1. Introdução

.

## 2. Visão geral do dataset

### 2.1. Importação dos pacotes

- `pandas`: manipulação e análise de dados tabulares;
- `numpy`: operações numéricas auxiliares;
- `pathlib`: path do dataset;
- `seaborn`: carregamento do dataset e visualização estatística;
- `matplotlib.pyplot`: configuração e exibição de gráficos.

In [7]:
import pandas as pd
import numpy as np
from pathlib import Path

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats

# Configurações visuais
sns.set_theme(style="whitegrid")
pd.set_option("display.max_columns", None)
pd.set_option("display.precision", 2)

# Caminho dataset
PATH_GOLD   = Path('../datasets/dataset_gold/')

print(f'Gold:   {PATH_GOLD.resolve()}')

Gold:   C:\Users\Nogueira\Documents\GitHub\Trabalho_ciencia_de_dados\datasets\dataset_gold

### 2.2. Carregamento do dataset

Cada linha representa um cliente.

In [3]:
df = pd.read_parquet(PATH_GOLD / "dataset_gold.parquet")

df.head()

,customer_id,primeira_compra,ultima_compra,recencia_dias,score_recencia,frequencia,score_frequencia,is_recomprador,score_frequencia_monetario,valor_monetario,score_monetario,ticket_medio,score_rfm,segmento_cliente
0,1,2024-03-01,2024-05-02,187,2,2,1,True,1,1096.70,1,548.35,4,Em Risco
1,2,2024-05-22,2024-05-22,167,2,1,1,False,3,4378.05,3,4378.05,6,Em Risco
2,3,2024-07-10,2024-07-10,118,3,1,1,False,3,3177.20,3,3177.20,7,Leal
3,4,2024-06-02,2024-06-02,156,3,1,1,False,1,670.56,1,670.56,5,Em Risco
4,5,2023-12-06,2023-12-06,335,1,1,1,False,4,6153.80,4,6153.80,6,Em Risco

### 2.3. Dimensão do dataset

In [4]:
linhas, colunas = df.shape

print(f"Número de linhas: {linhas}")
print(f"Número de colunas: {colunas}")

Número de linhas: 10000
Número de colunas: 14

### 2.4. Estrutura das variáveis

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 10000 non-null  int64
 1   primeira_compra             10000 non-null  datetime64[us]
 2   ultima_compra               10000 non-null  datetime64[us]
 3   recencia_dias               10000 non-null  int64
 4   score_recencia              10000 non-null  int64
 5   frequencia                  10000 non-null  int64
 6   score_frequencia            10000 non-null  int64
 7   is_recomprador              10000 non-null  bool
 8   score_frequencia_monetario  10000 non-null  int64
 9   valor_monetario             10000 non-null  float64
 10  score_monetario             10000 non-null  int64
 11  ticket_medio                10000 non-null  float64
 12  score_rfm                   10000 non-null  int64
 13  segmento_cliente            10000 non-null  str
dtypes: bool(1), datetime64[us](2), float64(2), int64(8), str(1)
memory usage: 1.1 MB

### 2.5. Valores ausentes

In [5]:
missing = df.isnull().sum()

missing

customer_id                   0
primeira_compra               0
ultima_compra                 0
recencia_dias                 0
score_recencia                0
frequencia                    0
score_frequencia              0
is_recomprador                0
score_frequencia_monetario    0
valor_monetario               0
score_monetario               0
ticket_medio                  0
score_rfm                     0
segmento_cliente              0
dtype: int64

Não foram identificados valores ausentes.

### 2.5. Valores duplicados

In [6]:
df.duplicated().sum()

np.int64(0)

Não foram identificados registros duplicados.

### 2.6. Identificação de variáveis numéricas e categóricas

In [9]:
numericas = df.select_dtypes(include="number").columns.tolist()
categoricas = df.select_dtypes(exclude="number").columns.tolist()

print("Variáveis numéricas:")
print(numericas)

print("\nVariáveis categóricas:")
print(categoricas)

Variáveis numéricas:
['customer_id', 'recencia_dias', 'score_recencia', 'frequencia', 'score_frequencia', 'score_frequencia_monetario', 'valor_monetario', 'score_monetario', 'ticket_medio', 'score_rfm']

Variáveis categóricas:
['primeira_compra', 'ultima_compra', 'is_recomprador', 'segmento_cliente']

### 2.7. Variáveis escolhidas para a análise

........................................

## 3. Descrição estatística

### 3.1. Resumo estatístico geral das variáveis numéricas

- `count`: quantidade de valores não ausentes;
- `mean`: média;
- `std`: desvio-padrão;
- `min`: menor valor;
- `25%`: primeiro quartil;
- `50%`: mediana;
- `75%`: terceiro quartil;
- `max`: maior valor.

In [10]:
df[numericas].describe()

,customer_id,recencia_dias,score_recencia,frequencia,score_frequencia,score_frequencia_monetario,valor_monetario,score_monetario,ticket_medio,score_rfm
count,10000.00,10000.00,10000.00,10000.0,10000.0,10000.00,10000.00,10000.00,10000.00,10000.00
mean,5000.50,168.74,2.50,1.2,1.0,2.50,3402.31,2.50,2831.02,6.00
std,2886.90,104.62,1.12,0.4,0.0,1.12,2738.80,1.12,2153.52,1.64
min,1.00,1.00,1.00,1.0,1.0,1.00,24.58,1.00,24.58,3.00
25%,2500.75,77.00,2.00,1.0,1.0,1.75,1140.45,1.75,1033.22,5.00
50%,5000.50,162.00,3.00,1.0,1.0,2.50,2720.95,2.50,2334.92,6.00
75%,7500.25,257.00,4.00,1.0,1.0,3.25,5049.95,3.25,4147.64,7.00
max,10000.00,366.00,4.00,2.0,1.0,4.00,19651.70,4.00,10082.72,9.00

### 3.2. Média e mediana das variáveis numéricas

In [11]:
media_mediana = pd.DataFrame({
    "media": df[numericas].mean(),
    "mediana": df[numericas].median()
})

media_mediana["diferenca_media_mediana"] = media_mediana["media"] - media_mediana["mediana"]

media_mediana

                              media  mediana  diferenca_media_mediana
customer_id                 5000.50  5000.50                 0.00e+00
recencia_dias                168.74   162.00                 6.74e+00
score_recencia                 2.50     3.00                -4.97e-01
frequencia                     1.20     1.00                 2.00e-01
score_frequencia               1.00     1.00                 0.00e+00
score_frequencia_monetario     2.50     2.50                 0.00e+00
valor_monetario             3402.31  2720.95                 6.81e+02
score_monetario                2.50     2.50                 0.00e+00
ticket_medio                2831.02  2334.92                 4.96e+02
score_rfm                      6.00     6.00                 2.80e-03

### 3.3. Mínimo, máximo e amplitude inicial das variáveis numéricas

In [12]:
limites = pd.DataFrame({
    "minimo": df[numericas].min(),
    "maximo": df[numericas].max()
})

limites["amplitude"] = limites["maximo"] - limites["minimo"]

limites

                            minimo    maximo  amplitude
customer_id                   1.00  10000.00    9999.00
recencia_dias                 1.00    366.00     365.00
score_recencia                1.00      4.00       3.00
frequencia                    1.00      2.00       1.00
score_frequencia              1.00      1.00       0.00
score_frequencia_monetario    1.00      4.00       3.00
valor_monetario              24.58  19651.70   19627.12
score_monetario               1.00      4.00       3.00
ticket_medio                 24.58  10082.72   10058.14
score_rfm                     3.00      9.00       6.00

### 3.5. Quartis das variáveis numéricas

In [13]:
quartis = df[numericas].quantile([0.25, 0.50, 0.75])
quartis.index = ["Q1_25%", "Q2_50%_mediana", "Q3_75%"]

quartis

,customer_id,recencia_dias,score_recencia,frequencia,score_frequencia,score_frequencia_monetario,valor_monetario,score_monetario,ticket_medio,score_rfm
Q1_25%,2500.75,77.0,2.0,1.0,1.0,1.75,1140.45,1.75,1033.22,5.0
Q2_50%_mediana,5000.50,162.0,3.0,1.0,1.0,2.50,2720.95,2.50,2334.92,6.0
Q3_75%,7500.25,257.0,4.0,1.0,1.0,3.25,5049.95,3.25,4147.64,7.0